version: '3'
services:
  master1:
    build:
      context: ./master
      dockerfile: Dockerfile.master
    volumes:
      - ./master/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  master2:
    build:
      context: ./master
      dockerfile: Dockerfile.master
    volumes:
      - ./master/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  master3:
    build:
      context: ./master
      dockerfile: Dockerfile.master
    volumes:
      - ./master/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  slave1:
    build:
      context: ./slave
      dockerfile: Dockerfile.slave
    volumes:
      - ./slave/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  slave2:
    build:
      context: ./slave
      dockerfile: Dockerfile.slave
    volumes:
      - ./slave/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  slave3:
    build:
      context: ./slave
      dockerfile: Dockerfile.slave
    volumes:
      - ./slave/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
